### ISSUE TITLE
[BE] 게시글 삭제 로직 구현 및 테스트

### ISSUE THREAD

**Issue by yangddoddi** [codestates-seb/seb40_main_004#29]
### 필수

- [x] 전체 로직 작성 및 검토
- [x] JSON 요청/반환 값 작성 및 검토
- [x] 응용 계층 테스트
- [x] 응용 계층 로직 구현
- [x] 비즈니스 계층 테스트
- [x] 비즈니스 로직 구현
- [ ] 통합 테스트
- [ ] 기능 테스트

### 해당사항 있는 경우

- [ ] 데이터 액세스 계층 테스트
- [ ] 데이터 액세스 계층 구현
- [ ] DTO 테스트
- [ ] DTO 구현
- [ ] Mapper 테스트
- [ ] Mapper 구현

**Comment by Shawn9948** [comment]
게시긇 삭제 컨트롤러 테스트에서 통과가 안되는 현상이 발견되었습니다. 하지만 서비스로직 테스트는 통과하였습니다. 
기능적인 문제보다는 테스트 코드의 문제가 있는것으로 보이므로 추후 시간내서 해결하도록 하겠습니다.
