### ISSUE TITLE
[dev-log] 박혜정 22-11-09

### ISSUE THREAD

**Issue by hyejj19** [codestates-seb/seb40_main_004#36]
### 😸 오늘 어떻게 프로젝트에 기여했나요?
- 페이지별 플로우 차트 완성 & 보완할 점 체크
- 메인 페이지 UI 와이어프레임 작업

### 😸 오늘의 프로젝트에서 힘든 점은 무엇인가요?
- 컨디션 점수 4점!
- UI 계획을 꼼꼼하게 하고 싶지만 시간이 부족한 것 같다는 느낌이 듭니다. 최선의 선택을 하는게 좋은 것 같아요.

### 😸 내일을 위해 기여해야 하는 일은?
- UI 와이어 프레임 작업
- 플로우 차트를 기반으로 각 페이지 와이어 프레임 작업
- 보완이 필요한 플로우차트 작업하기

**Comment by Tldkt** [comment]
고생하셨습니다! 컨디션이 4점뿐이라니,,! 이럴수가,,!! 오늘은 건강 뿜뿜한 하루 되시길 바랍니다~!!
