### ISSUE TITLE
BE 양은찬 2022/11/12

### ISSUE THREAD

**Issue by yangddoddi** [codestates-seb/seb40_main_004#57]
### 😸 오늘 어떻게 프로젝트에 기여했나요?
- api 문서화, 리팩터링

### 😸 오늘의 프로젝트에서 힘든 점은 무엇인가요?
- 없음

### 😸 내일을 위해 기여해야 하는 일은?
- 회의, api 개발 일정 관리, api 개발

**Comment by Shawn9948** [comment]
은찬님 미리 작성하는건 반칙입니다

**Comment by yangddoddi** [comment]
@Shawn9948 zzzz 날짜를 잘못 입력했네요
